language: python
python:
  - 3.3
  - nightly
  - pypy3
  - "2.7"
  - pypy
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install .
  - pip install nose coverage
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:
  - python setup.py nosetests --with-coverage --cover-package astar

after_sucess:
  coveralls
